name: Setup for Deploy

on:
  workflow_call:
    inputs:
      branch:
        description: Branch to deploy
        required: true
        type: string     

jobs:
  setup:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
    - id: auth
      uses: google-github-actions/auth@v2
      with:
        workload_identity_provider: projects/425991501736/locations/global/workloadIdentityPools/development/providers/github
        service_account: github@chirpradiodev.iam.gserviceaccount.com
